version: '3.9'

services:
  postgres-product:
    image: postgres:13.3
    container_name: postgres-product
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: danis
      POSTGRES_PASSWORD: danis
    ports:
      - "5431:5432"

  postgres-order:
    image: postgres:13.3
    container_name: postgres-order
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: danis
      POSTGRES_PASSWORD: danis
    ports:
      - "5432:5432"

  postgres-inventory:
    image: postgres:13.3
    container_name: postgres-inventory
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: danis
      POSTGRES_PASSWORD: danis
    ports:
      - "5433:5432"