version: '3.9'

services:
  postgres-product:
    image: postgres:13.3
    container_name: postgres-product
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: danis
      POSTGRES_PASSWORD: danis
    ports:
      - "5431:5431"